//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paivystyslista.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Paivystys
    {
        public int Paivystys_id { get; set; }

        [Display(Name = "Varauspäivä")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Pvm { get; set; }
        public string Paiva { get; set; }

        [Display(Name = "Alkuaika")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Alku { get; set; }

        [Display(Name = "Loppuaika")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Loppu { get; set; }
        public Nullable<decimal> Kesto { get; set; }
        public string EiKva { get; set; }
        public string Huom { get; set; }
        public string Paivystaja { get; set; }
        public string Lomat { get; set; }
    }
}
